spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**

jwt:
  secret: "this_is_a_super_secure_jwt_key_123456"
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  port: 8080
